# Generated by Django 5.1.6 on 2025-04-08 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPodAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_name', models.CharField(max_length=255, verbose_name='Pod名称')),
                ('ssh_port', models.IntegerField(verbose_name='SSH端口')),
                ('ssh_password', models.CharField(max_length=255, verbose_name='SSH密码')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户Pod访问',
                'verbose_name_plural': '用户Pod访问',
                'unique_together': {('user', 'pod_name')},
            },
        ),
    ]
