# Generated by Django 5.1.6 on 2025-04-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BearOSAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpodaccess',
            name='ssh_ip',
            field=models.CharField(default=0, max_length=255, verbose_name='SSHip'),
            preserve_default=False,
        ),
    ]
