# Generated by Django 5.1.6 on 2025-04-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BearOSAPI', '0002_userpodaccess_ssh_ip'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpodaccess',
            table='k8s_pod_access',
        ),
    ]
